site_name: App-Documentation
docs_dir: docsmd # onde acha o md
site_dir: docs # onde vai o site index
nav:
    - Home: index.md
    - Developer: DEVELOPER.md
    - API: Api.md
    - AWS: PublicandoAWS.md
theme: readthedocs
